#include <cstddef>
#include <cstdlib>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <vector>
#include <ctime>
#include <print>
#include <map>

#include "base/abc/abc.h"

#include "map.hpp"

using namespace abc;

namespace fox::supper {
template <typename  T, prune_mode_t M> void
Prune<T, M>::print() const
{
    auto &ss = std::cout;
    ss << "Prune stats:\n";
    if constexpr (M == prune_mode_t::Unified) {
        ss << " unified set size : " << _unified_set.size();
        for (const T &item : _unified_set) {
            if constexpr (std::is_pointer_v<T>) {
                ss << "  " << **item << "\n";
            } else {
                ss << "  " << *item << "\n";
            }
        }
    } else {
        ss << " separated set size : " << _separated_set.size() - 1 << "\n";
        for (int i = 2; i != _separated_set.size(); ++i) {
            ss << "[" << i << "]\n";
            for (const T &item : _separated_set[i]) {
                if constexpr (std::is_pointer_v<T>) {
                    ss << "  " << **item << "\n";
                } else {
                    ss << "  " << *item << "\n";
                }
            }
        }
    }
}

template class Prune<Cut *, prune_mode_t::Unified  >;
template class Prune<Cut *, prune_mode_t::Separated>;

bool
graph_t::is_topologically_sorted() const
{
    // For a logic node, all of its fanins should be stored before it.
    ForEachGraphLogicNode(*this) {
        const auto &node = _nodes[idx];
        for (int i = 0; i != node.size(); ++i)
            if (node[i].id() > idx)
                return false;
    }
    return true;
}

void
graph_t::report(std::ostream &os)
{
    os << "graph stats: ";
    os << "PI "    << num_pi()    << "\t";
    os << "PO "    << num_po()    << "\t";
    os << "LOGIC " << num_logic() << "\t";
    os << "\n";
}

void *
graph_t::to_abc_ntk()
{
    Abc_Ntk_t *pNtk = Abc_NtkAlloc(ABC_NTK_LOGIC, ABC_FUNC_SOP, 1);
    if (!pNtk)
        return nullptr;

    return static_cast<void *>(pNtk);
}

bool
graph_t::to_dot(const std::string &path) const
{
    // Open file for writing
    FILE *fp = fopen(path.c_str(), "w");
    if (!fp) {
        std::cerr << "Failed to open file: " << path << std::endl;
        return false;
    }

    // Write DOT file header
    fprintf(fp, "digraph G {\n");
    
    // Set up graph properties
    fprintf(fp, "  graph [rankdir=TB];\n");
    fprintf(fp, "  node [shape=ellipse, style=filled, fillcolor=lightgrey];\n");
    
    // Define nodes
    for (int idx = begin(); idx != end(); ++idx) {
        const auto &node = _nodes[idx];
        if (node.null()) continue;
        
        if (node.is_pi()) {
            // PI nodes as downward triangles
            fprintf(fp, "  n%d [shape=invtriangle, fillcolor=lightblue, label=\"PI %d\"];\n", idx, idx);
        } else if (node.is_po()) {
            // PO nodes as upward triangles
            fprintf(fp, "  n%d [shape=triangle, fillcolor=lightgreen, label=\"PO %d\"];\n", idx, idx);
        } else if (node.is_logic()) {
            // Logic nodes as ellipses with IDs
            fprintf(fp, "  n%d [shape=ellipse, fillcolor=white, label=\"%d\"];\n", idx, idx);
        }
    }
    
    // Define edges
    for (int idx = begin(); idx != end(); ++idx) {
        const auto &node = _nodes[idx];
        if (node.null()) continue;
        
        for (uint i = 0; i < node.size(); ++i) {
            Lit fanin = node[i];
            // If sign is true (inverted input), use dashed line, otherwise solid
            const char* style = fanin.sign() ? "dashed" : "solid";
            fprintf(fp, "  n%d -> n%d [style=%s];\n", fanin.id(), idx, style);
        }
    }
    
    // Close the graph
    fprintf(fp, "}\n");
    
    // Close the file
    fclose(fp);
    
    return true;
}

bool
graph_t::write_to_verilog(const std::string &path) const
{
    // Open file for writing
    FILE *fp = fopen(path.c_str(), "w");
    if (!fp) {
        std::cerr << "Failed to open file: " << path << std::endl;
        return false;
    }
    
    // Generate a module name based on the file path
    std::string module_name = "circuit";
    size_t last_slash = path.find_last_of("/\\");
    size_t last_dot = path.find_last_of(".");
    if (last_slash != std::string::npos && last_dot != std::string::npos) {
        module_name = path.substr(last_slash + 1, last_dot - last_slash - 1);
    }
    
    // Write Verilog module header
    fprintf(fp, "// Verilog netlist generated by FoxSYN\n");
    fprintf(fp, "module %s(\n", module_name.c_str());
    
    // Write module ports
    // First, declare all inputs (PIs)
    if (num_pi() > 0) {
        fprintf(fp, "    // Primary inputs\n");
        for (uint i = 0; i < num_pi(); ++i) {
            fprintf(fp, "    input wire pi%d%s\n", i, (i == num_pi() - 1 && num_po() == 0) ? "" : ",");
        }
    }
    
    // Then, declare all outputs (POs)
    if (num_po() > 0) {
        fprintf(fp, "    // Primary outputs\n");
        for (uint i = 0; i < num_po(); ++i) {
            fprintf(fp, "    output wire po%d%s\n", i, (i == num_po() - 1) ? "" : ",");
        }
    }
    
    fprintf(fp, ");\n\n");
    
    // Declare internal wires for logic nodes
    if (num_logic() > 0) {
        fprintf(fp, "    // Internal wires\n");
        for (int idx = begin(); idx != end(); ++idx) {
            const auto &node = _nodes[idx];
            if (!node.null() && node.is_logic()) {
                fprintf(fp, "    wire n%d;\n", idx);
            }
        }
        fprintf(fp, "\n");
    }
    
    // Write the logic for each node
    // Process PI nodes - assign to nodes
    for (uint i = 0; i < num_pi(); ++i) {
        uint pi_id = _pi[i];
        fprintf(fp, "    // PI node %d\n", pi_id);
        fprintf(fp, "    wire n%d = pi%d;\n", pi_id, i);
    }
    fprintf(fp, "\n");
    
    // Process logic nodes
    fprintf(fp, "    // Logic nodes\n");
    for (int idx = begin(); idx != end(); ++idx) {
        const auto &node = _nodes[idx];
        if (!node.null() && node.is_logic()) {
            fprintf(fp, "    // Node %d\n", idx);
            
            // For a 2-input logic node (AND gate with possible inversions)
            if (node.size() == 2) {
                Lit fanin0 = node[0];
                Lit fanin1 = node[1];
                
                // Handle potential inversions on inputs
                const char* in0 = fanin0.sign() ? "~" : "";
                const char* in1 = fanin1.sign() ? "~" : "";
                
                fprintf(fp, "    assign n%d = %sn%d & %sn%d;\n", 
                        idx, in0, fanin0.id(), in1, fanin1.id());
            }
            // Handle nodes with single fanin (e.g., buffers or inverters)
            else if (node.size() == 1) {
                Lit fanin0 = node[0];
                const char* in0 = fanin0.sign() ? "~" : "";
                fprintf(fp, "    assign n%d = %sn%d;\n", idx, in0, fanin0.id());
            }
        }
    }
    fprintf(fp, "\n");
    
    // Process PO nodes
    for (uint i = 0; i < num_po(); ++i) {
        uint po_id = _po[i];
        const auto &node = _nodes[po_id];
        
        fprintf(fp, "    // PO node %d\n", po_id);
        
        if (node.size() == 1) {
            Lit fanin = node[0];
            const char* in_sign = fanin.sign() ? "~" : "";
            fprintf(fp, "    assign po%d = %sn%d;\n", i, in_sign, fanin.id());
        }
        else {
            // If PO has no fanin, assign it a constant 0
            fprintf(fp, "    assign po%d = 1'b0; // No fanin\n", i);
        }
    }
    
    // Close the module
    fprintf(fp, "endmodule\n");
    
    // Close the file
    fclose(fp);
    
    return true;
}

void
MappingPass::improve_mapping_exactly(mapper &mgr)
{
    TIME_START(T)
    ForEachGraphLogicNode(mgr)
    {
        const Cut *best_cut = mgr.best_cut(idx);
        if (mgr.num_est_ref(idx))
            mgr.rip_mffc(best_cut);
        CutCost best_cost(mgr.rip_mffc(best_cut), mgr.ref_mffc(best_cut));
        auto cut_set = mgr.cut_set(idx);
        for (int k = 0; k != cut_set.size() - 1; ++k)
        {
            Cut *cut = cut_set[k];
            CutCost cost(mgr.rip_mffc(cut), mgr.ref_mffc(cut));
            if (mgr.compare(best_cost, cost) == CutCost::cmp_res::RWIN)
            {
                best_cut = cut;
                best_cost = cost;
            }
        }

        if (mgr.num_est_ref(idx))
            mgr.ref_mffc(best_cut);

        if (best_cut != mgr.best_cut(idx)) {
            mgr.set_best_cut(idx, best_cut);
        }
    }

    mgr.num_area() = 0;
    mgr.num_edge() = 0;
    ForEachGraphLogicNode(mgr) {
        if (mgr.num_est_ref(idx)) {
            mgr.num_area() ++;
            mgr.num_edge() += mgr.best_cut(idx)->size;
        }
    }

    if (mgr.config().verbose) {
        TIME_STOP(T)
        std::println(std::cout, INFO3, mgr.num_area(), mgr.num_edge(), Timer::formatted_time(cpu_T, 5));
    }
}

void
mapper::print_node(uint id)
{
    std::cout << "node id : " << id << "\n";
    std::cout << " type " << (uint)_nodes[id].type() << "\n";
    std::cout << " size " << _nodes[id].size() << "\n";
    for (int i = 0; i != _nodes[id].size(); ++i) {
        std::cout << "  fanin " << i << " : " << _nodes[id][i].val() << "\n";
    }
    std::cout << " cuts\n";
    for (const auto &cut : _cuts[id]) {
        std::cout << "  cut " << **cut << "\n";
    }
    std::cout << " best cut " << **best_cut(id) << "\n";
}

mapper *
mapper::create_from_aig(void *ntk)
{
    Abc_Ntk_t *pNtk = static_cast<Abc_Ntk_t *>(ntk);
    if (pNtk->ntkFunc != ABC_FUNC_AIG || pNtk->ntkType != ABC_NTK_STRASH) {
        std::cout << "unsupported ntk type\n";
        return nullptr;
    }

    mapper *mgr = new mapper(Abc_NtkObjNumMax(pNtk), Abc_NtkPiNum(pNtk), Abc_NtkPoNum(pNtk));

    mgr->timer().start("create_graph");

    for (int n = 0; n != pNtk->vObjs->nSize; ++n) {
        Abc_Obj_t *pObj = Abc_NtkObj(pNtk, n);
        if (!pObj) [[unlikely]] {
            mgr->_nodes.emplace_back(graph_t::node_type_t::NONE);
            continue;
        }
        switch (pObj->Type) {
            case ABC_OBJ_CONST1:
                assert(mgr->_nodes.size() == 0);
                mgr->_nodes.emplace_back(graph_t::node_type_t::ONE);
                break;
            case ABC_OBJ_PI:
                mgr->_nodes.emplace_back(graph_t::node_type_t::PI);
                mgr->_pi.push_back(mgr->_nodes.size() - 1);
                mgr->_pi_names.push_back(Abc_ObjName(pObj));
                break;
            case ABC_OBJ_PO:
                mgr->_nodes.emplace_back(graph_t::node_type_t::PO, Lit(Abc_ObjFaninId0(pObj), pObj->fCompl0));
                mgr->_po.push_back(mgr->_nodes.size() - 1);
                mgr->_po_names.push_back(Abc_ObjName(pObj));
                break;
            case ABC_OBJ_NODE: [[likely]]
                mgr->_nodes.emplace_back(graph_t::node_type_t::LOGIC,
                    Lit(Abc_ObjFaninId0(pObj), pObj->fCompl0), Lit(Abc_ObjFaninId1(pObj), pObj->fCompl1));
                break;
            default:
                assert(0 && "unknown abc object type");
                mgr->_nodes.emplace_back(graph_t::node_type_t::NONE);
                break;
        }
    }

    mgr->initialize();

    mgr->timer().stop("create_graph");

    return mgr;
}

void
mapper::initialize()
{
    // move to create_from_aig ...
    for (int i = 0; i != num_nodes(); ++i) {
        const node_t &n = _nodes[i];
        for (int k = 0; k != n.size(); ++k)
            ++_int_ref[n[k]];
    }

    for (int i = 0; i != _est_ref.size(); ++i)
        _est_ref[i] = _int_ref[i];
}

word
mapper::compute_truth(const Cut *cut, uint root) const
{
    static constexpr word init_val[6] = {
        0xAAAAAAAAAAAAAAAA,
        0xCCCCCCCCCCCCCCCC,
        0xF0F0F0F0F0F0F0F0,
        0xFF00FF00FF00FF00,
        0xFFFF0000FFFF0000,
        0xFFFFFFFF00000000
    };

    _timer.start("compute_truth");

    if (cut->size == 2 && _nodes[root][0].id() == cut->leaf(0) && _nodes[root][1].id() == cut->leaf(1)) {
        word t0 = init_val[0];
        word t1 = init_val[1];
        if (_nodes[root][0].sign())
            t0 = ~t0;
        if (_nodes[root][1].sign())
            t1 = ~t1;
        return t0 & t1;
    }

    std::map<uint, word> cache;

    const uint min_id = cut->leaf(0);
    ForEachCutLeaf(cut) {
        cache[leaf - min_id] = init_val[i];
    }

    std::function<void(uint)> fn = [&](uint n) {
        const auto &node = _nodes[n];
        assert(cache[n - min_id] == 0);
        assert(node.size() == 2);
        if (cache[node[0].id() - min_id] == 0)
            fn(node[0].id());
        if (cache[node[1].id() - min_id] == 0)
            fn(node[1].id());
        word t0 = cache[node[0].id() - min_id];
        word t1 = cache[node[1].id() - min_id];
        if (node[0].sign())
            t0 = ~t0;
        if (node[1].sign())
            t1 = ~t1;
        cache[n - min_id] = t0 & t1;
    };

    fn(root);

    _timer.stop("compute_truth");

    return cache[root - min_id];
}

Area
mapper::ref_mffc(const Cut *cut)
{
    Area area = 1.0;
    ForEachCutLeaf(cut) {
        if (num_est_ref(leaf)++ > 0 || !_nodes[leaf].is_logic())
            continue;
        area += ref_mffc(best_cut(leaf));
    }
    return area;
}

Edge
mapper::rip_mffc(const Cut *cut)
{
    Edge edge = cut->size;
    ForEachCutLeaf(cut)
    {
        assert(num_est_ref(leaf) > 0);
        if (--num_est_ref(leaf) > 0 || !_nodes[leaf].is_logic())
            continue;
        edge += rip_mffc(best_cut(leaf));
    }
    return edge;
}

CutCost
mapper::compute_cut_cost(CutCostAlgo algo, Cut *cut)
{
    CutCost cost;
    switch (algo) {
    case CutCostAlgo::FLOW: {
        cost.size = cut->size;
        // area-flow/edge-flow
        ForEachCutLeaf(cut) {
            cost.area += area(leaf);
            cost.edge += edge(leaf);
        }
        // TODO: using cost library
        cost.area += 1.0;
        cost.edge += cut->size;
        break;
    }
    case CutCostAlgo::EXACT: {
        break;
    }
    case CutCostAlgo::PRAETOR: {
        break;
    }
    default:
        break;
    }
    return cost;
}

graph_t *
mapper::create_mapped_graph()
{
    graph_t *mapped = nullptr;

    return mapped;
}

void *
mapper::create_abc_ntk_from_mapping(bool use_truth_table)
{
    Abc_Ntk_t *ntk = use_truth_table ? Abc_NtkAlloc(ABC_NTK_LOGIC, ABC_FUNC_SOP, 1) : Abc_NtkAlloc(ABC_NTK_LOGIC, ABC_FUNC_AIG, 1);
    std::vector<Abc_Obj_t *> idx2obj(num_nodes(), nullptr);

    ForEachGraphPi(*this) {
        auto pi = Abc_NtkCreatePi(ntk);
        Abc_ObjAssignName(pi, const_cast<char *>(get_pi_name(idx).c_str()), nullptr);
        idx2obj[_pi[idx]] = pi;
    }
    ForEachGraphPo(*this) {
        auto po = Abc_NtkCreatePo(ntk);
        Abc_ObjAssignName(po, const_cast<char *>(get_po_name(idx).c_str()), nullptr);
        idx2obj[_po[idx]] = po;
    }

    auto create_sop_node = [&](uint idx, Abc_Obj_t *pConst1) {
        const Cut *cut = best_cut(idx);
        word truth = compute_truth(cut, idx);
        Abc_Obj_t *pLut = Abc_NtkCreateObj(ntk, ABC_OBJ_NODE);
        if (truth == 0ul || truth == ~0ul) [[unlikely]] {
            Abc_ObjAddFanin(pLut, pConst1);
            if (truth == 0ul)
                pLut->pData = Abc_SopCreateBuf((Mem_Flex_t *)ntk->pManFunc);
            else
                pLut->pData = Abc_SopCreateInv((Mem_Flex_t *)ntk->pManFunc);
        } else {
            pLut->pData = Abc_SopRegister((Mem_Flex_t*)ntk->pManFunc, Abc_SopCreateFromTruth((Mem_Flex_t *)ntk->pManFunc,
                cut->size, (unsigned *)&truth));
            for (int m = 0; m != cut->size; ++m)
                Abc_ObjAddFanin(pLut, idx2obj[cut->begin()[m]]);
        }
        return pLut;
    };

    if (use_truth_table) {
        Abc_Obj_t *pConst1 = Abc_NtkCreateNodeConst1(ntk);
        // Hook the pwr
        idx2obj[pwr()] = pConst1;

        ForEachGraphLut(*this) {
            idx2obj[idx] = create_sop_node(idx, pConst1);
        }

        ForEachGraphPoV(*this) {
            const node_t &po = get_po(idx);
            if (po[0].sign()) {
                Abc_Obj_t *pInv = Abc_NtkCreateNodeInv(ntk, idx2obj[po[0].id()]);
                Abc_ObjAddFanin(idx2obj[po_id(idx)], pInv);
            } else {
                Abc_ObjAddFanin(idx2obj[po_id(idx)], idx2obj[po[0].id()]);
            }
        }

        // remove it if not used
        if (Abc_ObjFanoutNum(pConst1) == 0)
            Abc_NtkDeleteObj(pConst1);
    } else {

    }

    return static_cast<void *>(ntk);
}

void
mapper::create_simple_gates(uint max_size)
{
    mapper &mgr = *this;

    // mgr.to_dot("graph.dot");
    // std::system("dot -Tpdf graph.dot -o graph.pdf");
    // std::system("cp graph.pdf /mnt/c/Users/chang/Desktop/");
    // std::system("rm graph.dot");

    _timer.start("create_gate");
    _gates.resize(num_nodes(), nullptr);

    // find the gate roots at first
    std::fill(_gates.begin(), _gates.begin() + mgr.num_pi() + 1, (Gate *)01);
    ForEachGraphPoV(mgr) {
        _gates[n[0]] = (Gate *)01;
    }
    ForEachGraphLogicNodeRev(mgr) {
        if (mgr.num_ref(idx) > 1) {
            _gates[idx] = (Gate *)01;
        }
        const auto &n = mgr[idx];
        for (int i = 0; i != n.size(); ++i) {
            if (n[i].sign()) {
                _gates[n[i]] = (Gate *)01;
            }
        }
    }

    std::function<void(Lit, Array<Lit> &)> fn = [&](Lit id, Array<Lit> &inputs) {
        if (_gates[id]) {
            inputs.push_unique(id);
        } else {
            for (int i = 0; i != mgr[id].size(); ++i) {
                if (inputs.size() >= max_size)
                    break;
                fn(mgr[id][i], inputs);
            }
        }
    };

    // create simple gates
    ForEachGraphLogicNodeRev(*this) {
        if (_gates[idx] == (Gate *)01) {
            Array<Lit> inputs; inputs.reserve(max_size);
            for (int i = 0; i != mgr[idx].size(); ++i) {
                fn(mgr[idx][i], inputs);
            }
            for (Lit i : inputs) {
                assert(_gates[i] == (Gate *)01);
            }
            Gate *gate = new Gate(std::move(inputs));
            _gates[idx] = gate;
        }
    }

    int num_gate = 0;
    std::map<int, int> size2num;
    // int id = 0;
    for (Gate *gate : _gates) {
        if (gate && gate != (Gate *)01) {
            ++num_gate;
            ++size2num[gate->size()];
            // std::cout << id << "\n";
        }
        // ++id;
    }

    for (CREF [size, number] : size2num) {
        LOG(std::cout, "  gate size {} : {}", size, number);
    }

    _timer.stop("create_gate");
}

graph_t *
mapper::run_lut_mapping(const Config &cfg)
{
    _cfg     = cfg;
    _rank_fn = CutCost::GetRankFn(cfg.opt_target);

    // Setup PI cuts
    constexpr uint kTrivCutMemSize = Cut::bytes_needed<Cut::KCUT>(1);
    void *pi_triv_cuts = std::calloc(1, kTrivCutMemSize * num_pi());
    {
        char *p = reinterpret_cast<char *>(pi_triv_cuts);
        ForEachGraphPi(*this) {
            uint id         = _pi[idx];
            Cut *cut        = reinterpret_cast<Cut *>(p);
            cut->sign       = SIGNATURE(id);
            cut->size       = 1;
            cut->begin()[0] = id;
            _cuts[id].push_back(cut);
            p += kTrivCutMemSize;
        }
        Assert(p == (reinterpret_cast<char *>(pi_triv_cuts) + kTrivCutMemSize * num_pi()));
    }

    // Setup best cuts
    const uint kBestCutMemSize = Cut::bytes_needed<Cut::KCUT>(cfg.lut_size);
    Assert(_nodes[logic_begin()].is_logic());
    _best_cuts.set_offset(logic_begin());
    _best_cuts.resize(num_logic(), nullptr);
    ForEachGraphLogicNode(*this) {
        Cut *cut = (Cut *)std::calloc(1, kBestCutMemSize);
        cut->ms  = kBestCutMemSize;
        _best_cuts[idx] = cut;
    }

    // create simple gates boundry
    if (run_agdmap()) {
        create_simple_gates(8);
    }

    // according to run-time parameters, choose mapping algorithm

    int num_pass_flow  = 3;
    int num_pass_exact = 1;

    for (int i = 0; i != num_pass_flow; ++i) {
        MappingPass(CutCostAlgo::FLOW, *this, i);
    }

    // for (int i = 0; i != num_pass_exact; ++i) {
    //     MappingPass(CutCostAlgo::EXACT, *this, i);
    // }

    std::free(pi_triv_cuts);
    return create_mapped_graph();
}


Abc_Ntk_t *PerformSupperMap(Abc_Ntk_t *pNtk, const Config &cfg)
{
    TIME_START(ALL);

    ///////////////////////////////////////
    mapper *mgr = mapper::create_from_aig(static_cast<void *>(pNtk));
    ///////////////////////////////////////

    if (!mgr) [[unlikely]] {
        std::println(std::cout, "SuperMap: failed to create mapper.");
        return nullptr;
    }

    if (cfg.verbose) {
        std::println(std::cout, ">>> SuperMap Started");
        std::println(std::cout, "    graph info: PI = {}, PO = {}, LOGIC = {}", mgr->num_pi(), mgr->num_po(), mgr->num_logic());
    }

    mgr->timer().start("lut_mapping");
    ///////////////////////////////////////
    graph_t *g = mgr->run_lut_mapping(cfg);
    ///////////////////////////////////////
    mgr->timer().stop ("lut_mapping");

    mgr->timer().start("create_abc_ntk");
    ///////////////////////////////////////
    Abc_Ntk_t *res_ntk = static_cast<Abc_Ntk_t *>(g ? g->to_abc_ntk() : mgr->create_abc_ntk_from_mapping());
    ///////////////////////////////////////
    mgr->timer().stop ("create_abc_ntk");

    TIME_STOP(ALL);

    if (cfg.verbose) {
        std::println(std::cout, ">>> Runtime Report");
        std::println(std::cout, "  Total CPU  Time {}  ", Timer::formatted_time(cpu_ALL,  5));
        std::println(std::cout, "  Total Wall Time {}\n", Timer::formatted_time(wall_ALL, 5));
        mgr->timer().report(std::cout);
    }

    ///////////////////////////////////////
    delete g;
    delete mgr;
    ///////////////////////////////////////

    return res_ntk;
}

}
